# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-01 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(default=b'N/A', max_length=50)),
                ('site_location', models.CharField(default=b'N/A', max_length=50)),
                ('site_area', models.BigIntegerField(default=1200)),
                ('site_cost', models.BigIntegerField(default=50000)),
                ('email_id', models.CharField(default=b'', max_length=100)),
                ('password', models.CharField(default=b'', max_length=18)),
                ('salt', models.CharField(default=b'', max_length=64)),
            ],
            options={
                'db_table': 'table',
            },
        ),
    ]
